version: "3"
services:
  mysql:
    image: mysql:5.7.21
    environment:
        - MYSQL_RANDOM_ROOT_PASSWORD="yes"
        - MYSQL_HOST
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    command: mysqld --lower_case_table_names=1 --skip-ssl
    ports:
        - "3306:3306"